# Generated by Django 4.1.3 on 2023-06-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexparagraf',
            name='image',
        ),
    ]
