# Generated by Django 4.1.3 on 2023-06-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_remove_indexparagraf_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexparagraf',
            name='image',
            field=models.FileField(default=2, upload_to=None, verbose_name='Kullanıcı Profil Fotorafı'),
            preserve_default=False,
        ),
    ]
